dev: &common
  delay: 300000 # -> 300s
  # blockchain_url: https://kovan.infura.io
  # blockchain_url: https://kovan.kyber.network
  blockchain_url: http://blockchain:8545
  # blockchain_url: http://blockchain:8540 # dev_chain_wrapper_with DELAY
  addresses: shared/deployment_dev.json
  balances: data/cex_initial_balance.json

ropsten:
  <<: *common
  blockchain_url: https://ropsten.infura.io
  addresses: shared/deployment_ropsten.json

kovan:  
  <<: *common
  blockchain_url: https://kovan.infura.io
  addresses: shared/deployment_kovan.json

simulation:
  <<: *common
  delay: 10000 # -> 10s
  # blockchain_url: http://blockchain:8545
  blockchain_url: http://dev_chain_wrapper:8540 # use dev_chain_wrapper with DELAY
  addresses: shared/deployment_dev.json

staging:
  <<: *common
  addresses: shared/deployment_staging.json
  
production:
  <<: *common

logging:
  version: 1
  disable_existing_loggers: True

  formatters:
    simple:
      format: '%(asctime)s - %(name)10s - %(levelname)7s - %(message)s - [%(filename)s:%(lineno)d:%(funcName)s]'

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: simulator.log
      maxBytes: 104857600 # 100MB
      backupCount: 2
      encoding: utf8

  loggers:
    simulator:
      level: DEBUG
      handlers: [console, file_handler]
      propagate: no
    dev_chain_wrapper:
      level: DEBUG
      handlers: [console, file_handler]
      propagate: no
      
  root:
    level: DEBUG
    handlers: [file_handler]

exchanges:
  binance:
    pk: 'cf0994187eedbeb765dd931372b75d542fd121577911486605352b32c1764b1e'
    supported_tokens: ['eth', 'omg', 'knc', 'eos', 'snt', 'elf', 'powr', 'mana', 'bat', 'req', 'gto', 'rdn', 'appc', 'eng', 'salt']
  huobi:
    pk: '628fee3875f87594b24c773ca410c5e5e25ad142bf2eef5ea9fc56018064fbad'
    supported_tokens: ['eth', 'omg', 'eos', 'elf', 'powr', 'mana', 'bat', 'req', 'rdn', 'appc', 'eng', 'salt']
  bittrex:
    pk: '7e72df544ce569ccd35b53a2e8411aaefebad8bb42b2ef443593663b1979ac9b'
    supported_tokens: ['eth', 'omg', 'snt', 'powr', 'mana', 'bat', 'eng', 'salt']