version: "2.0"
services:
  simulator:
    build: .
    env_file:
      - common.env
    volumes:
      - .:/exchange-simulator      
    ports:
      - "5000:5000"
    command: python restful_api.py
    depends_on:
      - redis
  redis:
    image: "redis:alpine"